// One-off generator for supabase/seed.sql — reuses the exact seed data and
// mkBook()/seedBooks() logic from index.html so the real Supabase shelf
// matches the prototype's seed data exactly, byte for byte.
const fs = require('fs');
const path = require('path');
const src = fs.readFileSync(path.join(__dirname, '..', 'index.html'), 'utf8');
const grab = re => { const m = src.match(re); if (!m) throw new Error('missing ' + re); return m[0]; };

const code = [
  grab(/const SEED = \[[\s\S]*?\r?\n\];/),
  grab(/const CURRENT_BOOK = [^\r\n]*/),
  grab(/const PREVIOUSLY_READ = \[[\s\S]*?\r?\n\];/),
  grab(/const olCover = [^\r\n]*/),
  grab(/const amazonURL = [^\r\n]*/),
  grab(/const FALLBACK = \[[\s\S]*?\];/),
  grab(/function mkBook[\s\S]*?\r?\n\}/),
  grab(/function seedBooks\(\)\{[\s\S]*?\r?\n\}/),
].join('\n') + '\nreturn {seedBooks};';

const { seedBooks } = new Function(code)();
const books = seedBooks();

const q = s => s == null ? 'null' : `'${String(s).replace(/'/g,"''")}'`;
const b = v => v ? 'true' : 'false';

let out = `-- Generated by scripts/gen_seed_sql.js from index.html's SEED / CURRENT_BOOK /
-- PREVIOUSLY_READ arrays — run once against a fresh schema.sql. Regenerate
-- and re-run only if the club's actual shelf changes; this does not touch
-- votes, meetings, or anything the organizer has since edited.

insert into books (id, title, author, isbn, cover_url, cover_large, amazon, c1, c2, glyph,
  status, added_at, by_token, needs_review, meetings_considered, zero_vote_streak,
  shortlist_misses, ever_shortlisted, archive_reason, archived_at, date_read)
values
`;

out += books.map(x => `  (${[
  q(x.id), q(x.title), q(x.author), q(x.isbn), q(x.coverURL), q(x.coverLarge), q(x.amazon),
  q(x.c1), q(x.c2), q(x.glyph), q(x.status), q(x.addedAt), q(x.byToken), b(x.needsReview),
  x.meetingsConsidered, x.zeroVoteStreak, x.shortlistMisses, b(x.everShortlisted),
  q(x.archiveReason), q(x.archivedAt), q(x.dateRead),
].join(', ')})`).join(',\n') + ';\n\n';

const currentId = books.find(x => x.status === 'current').id;
out += `update club set current_book_id = ${q(currentId)} where id = true;\n\n`;

const activeIds = books.filter(x => x.status === 'active').map(x => x.id);
out += `-- The one meeting members and the organizer see until the first round opens.
insert into meetings (candidate_ids)
values (array[${activeIds.map(q).join(', ')}]);
`;

fs.writeFileSync(path.join(__dirname, '..', 'supabase', 'seed.sql'), out);
console.log('wrote supabase/seed.sql —', books.length, 'books,', activeIds.length, 'active candidates');
